version: "3.9"
services: 
    api:
        build: .
        ports:
            - "8000:8000"
        environment:
            - DATABASE_HOSTNAME=postgres
            - DATABASE_PORT=5432
            - DATABASE_PASSWORD=birmingham
            - DATABASE_NAME=fastapi
            - DATABASE_USERNAME=postgres
            - SECRET_KEY=gqvwehbdwfwjejj32sghht6476tyfgn
            - ALGORITHM=HS256
            - ACCESS_TOKEN_EXPIRE_MINUTES=30
#         #command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
#         #depends_on:
#          #     - postgres 
#     postgres:
#         image: postgres
#         environment:po
#             - POSTGRES_PASSWORD=birmingham
#             - POSTGRES_USER=postgres
#             - POSTGRES_DB=fastapi

#         volumes:
#             - postgres-db:/var/lib/postgresql/data
        
#         ports: 
#            - 5433:5432
# volumes:
#     postgres-db: