version: "3"
services: 
    api:
        build: .
        ports:
            - 8000:8000
        #env_file:
        environment:
          - DATABASE_HOSTNAME=postgres
          - DATABASE_PORT=5432
          - DATABASE_PASSWORD=birmingham
          - DATABASE_NAME=fastapi
          - DATABASE_USERNAME=postgres
          - SECRET_KEY=gqvwehbdwfwjejj32sghht6476tyfgn
          - ALGORITHM=HS256
          - ACCESS_TOKEN_EXPIRE_MINUTES=30

    postgres:
        image: postgres
        environment:
            - POSTGRES_PASSWORD=birmingham
            - POSTGRES_DB=fatsapi

        volumes:
            - postgres-db:/var/lib/postgresql/data
volumes:
    postgres-db:
